lab7/myimgur/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("sign-up", views.SignUpView.as_view(), name="signup"),
    path("<int:user_id>", views.accounts, name="accounts"),
]

lab7/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:image_id>/", views.detail, name="detail"),
    path("<int:image_id>/comment", views.comment, name="comment"),
    path("<int:image_id>/comment/<int:comment_id>", views.comment_approve, name="comment_approve"),
    path("like_comment/<int:comment_id>", views.like, name="like_comment"),
    path("<int:image_id>/upvote", views.upvote, name="upvote"),
    path("<int:image_id>/downvote", views.downvote, name="downvote"),
    path("new", views.create_image, name="create_image"),
    path("<int:image_id>/edit", views.update_image, name="edit_image"),
    path("<int:image_id>/delete", views.delete_image, name="delete_image"),
]

lab7/myimgur/imgur/urls.py
from django.contrib import admin
from django.urls import include, path
from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("images/", include("app.urls")),
    path("", views.index, name="index"),
]

lab7/myimgur/app/templates/includes/approve_button.html
<form action="{% url 'app:comment_approve' image.id comment.id %}" method="post">
	{% csrf_token %}
	<button type="submit" class="btn btn-warning btn-outline-dark">Approve comment</button>
</form>

lab7/myimgur/app/templates/includes/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
	{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			{{ error }}
		{% endfor %}
	</div>
{% endif %}

{% for field in form.visible_fields %}
	<div class="row form-group">
		<div class="col-md-8 controls mx-auto">
			{{ field.label_tag }}
		{% if form.is_bound %}
			{% if field.errors %}
				{% render_field field class="form-control is-invalid" %}
				{% for error in field.errors %}
					<div class="invalid-feedback">
						{{ error }}
					</div>
				{% endfor %}
			{% else %}
				{% render_field field class="form-control is-valid" %}
			{% endif %}
		{% else %}
			{% render_field field class="form-control" %}
		{% endif %}
		</div>
	</div>
{% endfor %}

lab7/myimgur/app/templates/includes/comment.html
<div class="border comment">
	<p class="red">Posted by <a href="{% url 'accounts:accounts' comment.user.id %}">{{ comment.author }}</a> on {{ comment.created_at }} <strong>{{ message }}</strong></p>
	<p class="secondary">{{ comment.text }}</p>
</div>

lab7/myimgur/app/templates/includes/delete_image_link.html
<form
	action="{% url 'app:delete_image' image.id %}" ž
	method="post"
	id="delete_form_{{ image.id }}"
	class="hidden"
>
	{% csrf_token %}
</form>
<script type="text/javascript">
	$(document).on('click', "#delete_{{ image.id }}",
		() => $("#delete_form_{{ image.id }}").submit());
</script>

lab7/myimgur/app/templates/includes/like_button.html
<div>
	{% if user.is_authenticated and likeable %}
	<form
		action="{% url 'app:like_comment' comment.id %}"
		method="post"
		role="form"
		aria-label="form"
		class="form-inline float-right"
	>
		{% csrf_token %}
		<button type="submit" class="btn {{ like.like|yesno:'btn-success,btn-secondary' }}">
			+
		</button>
	</form>
	{% endif %}
	<span class="vote-score float-right display-4">Likes: {{ comment.like_score }}</span>
</div>

lab7/myimgur/app/templates/includes/vote_buttons.html
{% if user.is_authenticated %}
<div>
	<form
		action="{% url 'app:upvote' image.id %}"
		method="post"
		role="form"
		aria-label="form"
		class="form-inline float-left"
	>
		{% csrf_token %}
		<button type="submit" class="btn {{ vote.upvote|yesno:'btn-success,btn-secondary' }}">
			+
		</button>
	</form>
	<span class="vote-score float-left">{{ image.vote_score }}</span>
	<form
		action="{% url 'app:downvote' image.id %}"
		method="post"
		role="form"
		aria-label="form"
		class="form-inline float-left"
	>
		{% csrf_token %}
		<button type="submit" class="btn {{ vote.downvote|yesno:'btn-danger,btn-secondary' }}">
			-
		</button>
	</form>
</div>
{% endif %}